name: "📄 Product Requirement As Needed in YAML"
description: "Describe a new product requirement"
title: "[PRD] "
labels: ["type:prd"]
assignees: []

body:
  - type: input
    id: customer
    attributes:
      label: "👥 Customer / Stakeholder"
      description: "Who is requesting this requirement? (specific customer, customer segment, or internal team)"
      placeholder: ""
    validations:
      required: true

  - type: textarea
    id: revenue-impact
    attributes:
      label: "💰 Revenue Impact"
      description: "Estimate the revenue potential (direct, indirect, or cost savings). Include assumptions and time horizon."
      placeholder: ""
    validations:
      required: false

  - type: input
    id: required-date
    attributes:
      label: "📅 Required (Wish) Date"
      description: "When is this functionality ideally needed?"
      placeholder: ""
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: "📝 Summary / Business Case"
      description: "A short description of the requirement and why it matters."
      placeholder: ""
    validations:
      required: true

  - type: textarea
    id: detailed-requirement
    attributes:
      label: "🎯 Detailed Requirement"
      description: "Detailed description of what’s needed."
      placeholder: ""
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: "🔗 Links / References"
      description: "Add related issues, designs, mockups, or supporting docs."
      placeholder: ""
    validations:
      required: false
